// Generated by Wrangler by running `wrangler types`

interface Env {
        OPENAI_API_KEY: string;
        MCP_SERVER_URL: string;
        MCP_ENABLED: string;
        OPENAI_REALTIME_MODEL: string;
        /** token used for authenticating requests */
        AUTH_TOKEN: string;
}
